import { Inter } from "next/font/google"; // Import Inter from next/font/google
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] }); // Correctly use Inter

// Uncomment and adjust local fonts if needed
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
export const metadata = {
  title: "JobQuest AI",
  description: "Generated by create next app",


};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <link rel="icon" href="/JQLogo.png" type='image/png'/>
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
