import { Inter } from "next/font/google"; // Import Inter from next/font/google
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] }); // Correctly use Inter
export const metadata = {
  title: "JobQuest AI",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <link rel="icon" href="/JQLogo.png" type='image/png'/>
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
